import { TRPCReactProvider } from '@/trpc/react';
import '@startup-template/ui/styles/globals.css';

export const metadata = {
  title: 'Welcome to example-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
